# logging settings
x-logging-low: &logging-low
  driver: "json-file"
  options:
    max-file: 5
    max-size: 5m

x-logging-medium: &logging-medium
  driver: "json-file"
  options:
    max-file: 5
    max-size: 10m

x-logging-high: &logging-high
  driver: "json-file"
  options:
    max-file: 5
    max-size: 50m


services:

  mongo-db:
    image: mongo:4.4.13
    hostname: mongo-db
    container_name: "mongo-db"
    restart: always
    networks:
      - fiware
    logging: *logging-low
    volumes:
      - mongo-db:/data/db
  
  mongo-express:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: mongo-express
    depends_on:
      - mongo-db
    logging: *logging-low
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo-db:27017
    ports:
      - "8081:8081"
    networks:
      - fiware

  orion:
    image: fiware/orion:3.9.0 #Sometimes the latest builds fail. Hence, we recommend to use fixed, stable versions
    hostname: orion
    restart: always
    container_name: "orion"
    depends_on:
        - mongo-db
    networks:
        - fiware
    ports:
       - "1026:1026"
    command: -dbhost mongo-db -logLevel ERROR -noCache -logForHumans
    logging: *logging-high


  iot-agent:
    image: fiware/iotagent-json:1.21.1
    hostname: iot-agent
    container_name: "iot-agent"
    restart: always
    depends_on:
      - mongo-db
    ports:
      - "4041:4041"
    networks:
      - fiware
    logging: *logging-high
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_APPEND_MODE=true
      - IOTA_LOG_LEVEL=ERROR
      - IOTA_TIMESTAMP=true
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=false
      - IOTA_EXPLICIT_ATTRS=true
      - IOTA_MONGO_HOST=mongo-db
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagentjson
      - IOTA_PROVIDER_URL=http://iot-agent:4041
      - IOTA_DEFAULT_RESOURCE=/iot/json
      - IOTA_HTTP_PORT=7896
      - IOTA_MQTT_HOST=mosquitto
      - IOTA_MQTT_PORT=1883
      - IOTA_MQTT_PROTOCOL=mqtt
      - IOTA_MQTT_KEEPALIVE=60

  mosquitto:
    image: eclipse-mosquitto:2.0.14
    restart: always
    hostname: mosquitto
    container_name: mosquitto
    ports:
        - "1883:1883"
    networks:
        - fiware
    logging: *logging-low
    volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  quantumleap:
    image: orchestracities/quantumleap:0.8.3
    restart: always
    hostname: quantumleap
    container_name: quantumleap
    depends_on:
      - orion
      - crate
    networks:
      - fiware
    ports:
      - "8668:8668"
    environment:
      - CRATE_HOST=crate
      - LOGLEVEL=ERROR
    logging: *logging-high
      
  crate:
    image: crate:4.6.8
    restart: always
    hostname: crate
    container_name: crate
    networks:
        - fiware
    ports:
      - "4200:4200"
    volumes:
      - crate:/data
    environment: 
      - TZ=Europe/Berlin
      - CRATE_HEAP_SIZE=2g
    logging: *logging-low

  grafana:
    image: grafana/grafana:9.2.0
    restart: always
    container_name: grafana
    depends_on:
      - crate
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,grafana-simple-json-datasource,yesoreyeram-infinity-datasource
      - TZ=Europe/Berlin
    logging: *logging-low
    volumes:
      - "grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    networks:
      - fiware


volumes:
  mongo-db:
    name: mongodb
  crate:
    name: crate
  grafana:
    name: grafana

networks:
  fiware:
    name: fiware
